[config]
path = "/mirror/aosc-os"
retro_arches = ["armel", "armhf", "i486", "powerpc", "ppc64"]

[bulletin]
type = "info"
title = "Thank You for Choosing AOSC OS"
title-tr = "bulletin-title"
body = "AOSC OS strives to simplify your user experience and improve your day-to-day productivity."
body-tr = "bulletin-body"

[[mirrors]]
name = "Alibaba Cloud Open Source Mirror"
name-tr = "aliyun-name"
url = "https://mirrors.aliyun.com/anthon/aosc-os/"
loc = "China"
loc-tr = "aliyun-loc"

[[mirrors]]
name = "Beijing Foreign Studies University Open Source Mirror"
name-tr = "bfsu-name"
url = "https://mirrors.bfsu.edu.cn/anthon/aosc-os/"
loc = "China"
loc-tr = "bfsu-loc"

[[mirrors]]
name = "GeekPie (ShanghaiTech University) Open Source Mirror"
name-tr = "geekpie-name"
url = "https://mirrors.shanghaitech.edu.cn/anthon/aosc-os/"
loc = "China"
loc-tr = "geekpie-loc"

[[mirrors]]
name = "ISCAS Open Source Mirror"
name-tr = "iscas-name"
url = "https://mirror.iscas.ac.cn/anthon/aosc-os/"
loc = "China"
loc-tr = "iscas-loc"

[[mirrors]]
name = "Jilin University Open Source Mirror"
name-tr = "jlu-name"
url = "http://mirrors.jlu.edu.cn/anthon/aosc-os/"
loc = "China"
loc-tr = "jlu-loc"

[[mirrors]]
name = "LZUOSS Open Source Mirror"
name-tr = "lzu-name"
url = "https://mirror.lzu.edu.cn/anthon/aosc-os/"
loc = "China"
loc-tr = "lzu-loc"

[[mirrors]]
name = "Nanyang Institute of Technology Open Source Mirror (CIPS)"
name-tr = "nit-name"
url = "https://mirror.nyist.edu.cn/anthon/aosc-os/"
loc = "China"
loc-tr = "nit-loc"

[[mirrors]]
name = "NJU Mirror (Nanjing University)"
name-tr = "nju-name"
url = "https://mirror.nju.edu.cn/anthon/aosc-os/"
loc = "China"
loc-tr = "nju-loc"

[[mirrors]]
name = "SJTUG Mirror (Shanghai Jiao Tong University)"
name-tr = "sjtug-name"
url = "https://mirror.sjtu.edu.cn/anthon/aosc-os/"
loc = "China"
loc-tr = "sjtug-loc"

[[mirrors]]
name = "Tencent Open Source Software Mirror"
name-tr = "tencent-name"
url = "https://mirrors.cloud.tencent.com/anthon/aosc-os/"
loc = "China"
loc-tr = "tencent-loc"

[[mirrors]]
name = "Tsukuba WIDE Public Mirror service"
name-tr = "tsukuba-name"
url = "http://ftp.tsukuba.wide.ad.jp/Linux/anthon/aosc-os/"
loc = "Japan"
loc-tr = "tsukuba-loc"

[[mirrors]]
name = "Tsinghua Open Source Mirror (TUNA)"
name-tr = "tuna-name"
url = "https://mirrors.tuna.tsinghua.edu.cn/anthon/aosc-os/"
loc = "China"
loc-tr = "tuna-loc"

[[mirrors]]
name = "USTC Open Source Software Mirror"
name-tr = "ustc-name"
url = "https://mirrors.ustc.edu.cn/anthon/aosc-os/"
loc = "China"
loc-tr = "ustc-loc"

[[mirrors]]
name = "Netherlands Local Unix User Group (NLUUG) OSS Mirror"
name-tr = "nluug-name"
url = "https://ftp.nluug.nl/os/Linux/distr/anthon/aosc-os/"
loc = "Europe"
loc-tr = "nluug-loc"

[[mirrors]]
name = "xTom Open Source Software Mirror (Estonia)"
name-tr = "xtom-name"
url = "https://mirror.xtom.ee/anthon/aosc-os/"
loc = "Europe"
loc-tr = "xtom-loc"

[[mirrors]]
name = "xTom Open Source Software Mirror (Germany)"
name-tr = "xtom-name"
url = "https://mirror.xtom.de/anthon/aosc-os/"
loc = "Europe"
loc-tr = "xtom-loc"

[[mirrors]]
name = "xTom Open Source Software Mirror (Netherlands)"
name-tr = "xtom-name"
url = "https://mirror.xtom.nl/anthon/aosc-os/"
loc = "Europe"
loc-tr = "xtom-loc"

[[mirrors]]
name = "KoDDoS HK"
name-tr = "koddos-name"
url = "https://mirror-hk.koddos.net/anthon/aosc-os/"
loc = "Hong Kong"
loc-tr = "koddos-loc"

[[mirrors]]
name = "xTom Open Source Software Mirror (Hong Kong)"
name-tr = "xtom-name"
url = "https://mirror.xtom.com.hk/anthon/aosc-os/"
loc = "Hong Kong"
loc-tr = "xtom-loc"

[[mirrors]]
name = "Fastly CDN"
name-tr = "fastly-name"
url = "https://aosc-repo.freetls.fastly.net/aosc-os/"
loc = "Worldwide"
loc-tr = "fastly-loc"

[[mirrors]]
name = "xTom Open Source Software Mirror"
name-tr = "xtom-name"
url = "https://mirror.xtom.com/anthon/aosc-os/"
loc = "Worldwide"
loc-tr = "xtom-loc"

[distro.mainline.desktop]
name = "Desktop"
name-tr = "desktop-name"
description = "Our standard desktop distribution, powered by the KDE Plasma Desktop, which provides an extensive set of standard applications and features with a virtually unlimited amount of customizable settings, complete with an elegant interface."
description-tr = "desktop-description"

[distro.mainline."desktop+nvidia"]
name = "Desktop (with NVIDIA driver)"
name-tr = "desktop+nvidia-name"
description = "Our standard desktop distribution, powered by the KDE Plasma Desktop, which provides an extensive set of standard applications and features with a virtually unlimited amount of customizable settings, complete with an elegant interface (with pre-installed NVIDIA Proprietary Drivers)."
description-tr = "desktop+nvidia-description"

[distro.mainline.base]
name = "Base"
name-tr = "base-name"
description = "The Base variant provides a minimal set of features, just enough for you to get started. Base is still a pre-configured variant like other AOSC OS variants. Therefore, Base is suitable for performance constrained devices and servers."
description-tr = "base-description"

[distro.mainline.buildkit]
name = "BuildKit"
name-tr = "buildkit-name"
description = "BuildKit is essentially a non-bootable AOSC OS Base with full development support. This particular variant of AOSC OS comes with Autobuild3 and other AOSC OS packaging and maintenance tools, so that you could quickly get started with AOSC OS development or building packages for personal use."
description-tr = "buildkit-description"

[distro.mainline.server]
name = "Server"
name-tr = "server-name"
description = "Server releases are base system releases with additional tools for hosting remote files and Web contents, providing network routing, and other functions that enriches network access and resources for client devices."
description-tr = "server-description"

[distro.retro.desktop]
name = "Desktop"
name-tr = "retro-desktop-name"
description = "Full-featured release featuring the Trinity Desktop Environment, a spiritual successor to the venerable KDE 3.5. Experience the pinnacle of meticulous user interface design, still aspired by desktop environments of our day."
description-tr = "retro-desktop-description"

[distro.retro.base]
name = "Base"
name-tr = "retro-base-name"
description = "A base system release with a minimal set of applications and tools to get you started. This release is recommended for older, headless (non-graphical), or storage constrained systems."
description-tr = "retro-base-description"

[distro.retro.server]
name = "Server"
name-tr = "retro-server-name"
description = "A base system release bundled with server applications, for performance and storage contraint servers and older development boards."
description-tr = "retro-server-description"

[distro.retro.buildkit]
name = "BuildKit"
name-tr = "buildkit-name"
description = "BuildKit is essentially a non-bootable AOSC OS Base with full development support. This particular variant of AOSC OS comes with Autobuild3 and other AOSC OS packaging and maintenance tools, so that you could quickly get started with AOSC OS development or building packages for personal use."
description-tr = "buildkit-description"
