name: Rust

on: [push, pull_request]

env:
  DATABASE_URL: "sqlite://verify.db"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libsquashfs-dev libssl-dev pkg-config libsystemd-dev liblzma-dev libdbus-1-dev libzstd-dev
    - uses: actions/checkout@v3
    - name: Prepare database
      run: ./.ci/prepare.sh
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test
